DECLARE
v_user varchar2(30) := 'GRANITT';
v_password varchar2(30) := 'CHANGE ME';
v_pub_user varchar2(30) := v_user || '_PUB';


CURSOR C1 IS SELECT table_name FROM ALL_TABLES where owner= v_user;
v_table_name varchar2(30);
BEGIN

/* STEP 2 : Alter the source database */
BEGIN
EXECUTE IMMEDIATE 'ALTER DATABASE FORCE LOGGING';
EXECUTE IMMEDIATE 'ALTER DATABASE ADD SUPPLEMENTAL LOG DATA';
EXCEPTION WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE ('Unable to add supplemental log data : ' || SQLERRM );
END;

OPEN C1;
LOOP

FETCH C1 INTO v_table_name;
EXIT WHEN C1%NOTFOUND;

DBMS_OUTPUT.PUT_LINE ('Processing table ' || v_user || '.' || v_table_name);

DBMS_OUTPUT.PUT_LINE ('Adding supplemental log data');
BEGIN
EXECUTE IMMEDIATE  'ALTER TABLE ' || v_user || '.' || v_table_name || ' DROP SUPPLEMENTAL LOG DATA (ALL) COLUMNS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
EXECUTE IMMEDIATE  'ALTER TABLE ' || v_user || '.' || v_table_name || ' ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS';

DBMS_OUTPUT.PUT_LINE ('Preparing table instanciation');
DBMS_CAPTURE_ADM.PREPARE_TABLE_INSTANTIATION(TABLE_NAME => v_user || '.' || v_table_name );

END LOOP;
CLOSE C1;

EXECUTE IMMEDIATE 'CREATE USER '||v_user||'_PUB IDENTIFIED BY '||v_password||' DEFAULT TABLESPACE '||v_user||'_PUB QUOTA UNLIMITED ON SYSTEM QUOTA UNLIMITED ON SYSAUX';
EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || v_user || '_PUB';
EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO ' || v_user || '_PUB';
EXECUTE IMMEDIATE 'GRANT CREATE TABLESPACE TO ' || v_user || '_PUB';
EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ' || v_user || '_PUB';
EXECUTE IMMEDIATE 'GRANT SELECT_CATALOG_ROLE TO ' || v_user || '_PUB';
EXECUTE IMMEDIATE 'GRANT EXECUTE_CATALOG_ROLE TO ' || v_user || '_PUB';
EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO ' || v_user || '_PUB';
EXECUTE IMMEDIATE 'GRANT DBA TO ' || v_user || '_PUB';
EXECUTE IMMEDIATE 'GRANT EXECUTE on DBMS_CDC_PUBLISH TO ' || v_user || '_PUB';

DBMS_STREAMS_AUTH.GRANT_ADMIN_PRIVILEGE(GRANTEE => v_pub_user);

END;
/